//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryWord
    {
        public int Id { get; set; }
        public Nullable<int> IdWord { get; set; }
        public Nullable<int> IdAccount { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public Nullable<int> Time { get; set; }
        public string Remember { get; set; }
        public Nullable<bool> Learned { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
