//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordEffect
    {
        public int IdAccountUser { get; set; }
        public int IdWord { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> Review { get; set; }
        public Nullable<System.DateTime> DateMilli { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
